### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by Jzarecta** [lexansoft/etherid-js#1]
I am trying to install this, I am on Arch and using NodeJS 5.9.1, I installed Browserify 13, and I tried doing the bash build.bash script but i got this back:

```
$ bash build.bash 
Error: Cannot find module 'bs58' from '/home/jza/Downloads/etherid-js'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
build.bash: line 6: uglifyjs: command not found
Error: Cannot find module 'bs58' from '/home/jza/Downloads/etherid-js'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by lexansoft** [comment]
npm install bs58

Alexandre Naverniouk
